language: java

jdk:
  - openjdk8

os:
  - linux

dist: xenial

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - echo -e 'user = u\npassword = p' > local.properties

install:
  - sudo apt-get update
  - sudo apt-get install tesseract-ocr

script:
  - ./gradlew test

notifications:
  email: false
